-- MySQL Script generated by MySQL Workbench
-- Mon Oct 26 14:28:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema locadoraVeiculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadoraVeiculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadoraVeiculos` DEFAULT CHARACTER SET utf8 ;
USE `locadoraVeiculos` ;

-- -----------------------------------------------------
-- Table `locadoraVeiculos`.`Veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadoraVeiculos`.`Veiculos` (
  `IDVeiculos` INT NOT NULL,
  `dataAquisicao` DATE NOT NULL,
  `precoDiaria` DECIMAL(10,2) NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `statusVeiculo` VARCHAR(12) NOT NULL,
  `Veiculoscol` VARCHAR(45) NOT NULL,
  `ano` INT NOT NULL,
  `modelo` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`IDVeiculos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadoraVeiculos`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadoraVeiculos`.`Clientes` (
  `IDClientes` INT NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `numeroCNH` VARCHAR(11) NOT NULL,
  `dataValidadeCnh` DATE NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `nomeCliente` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `dateCadastro` DATE NOT NULL,
  `statusCliente` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`IDClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadoraVeiculos`.`Despachantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadoraVeiculos`.`Despachantes` (
  `IDDespachantes` INT NOT NULL,
  `nomeDespachante` VARCHAR(150) NOT NULL,
  `statusDespachante` VARCHAR(7) NOT NULL,
  `filial` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`IDDespachantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadoraVeiculos`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadoraVeiculos`.`Locacao` (
  `IDLocacao` INT NOT NULL,
  `dataLocacao` DATE NOT NULL,
  `dataEntrega` DATE NOT NULL,
  `total` DECIMAL (10,2) NOT NULL,
  `FK_IDClientes` INT NOT NULL,
  `FK_IDDespachante` INT NOT NULL,
  `FK_IDVeiculo` INT NOT NULL,
  PRIMARY KEY (`IDLocacao`, `FK_IDClientes`, `FK_IDDespachante`, `FK_IDVeiculo`),
  INDEX `fk_Locacao_Clientes_idx` (`FK_IDClientes` ASC),
  INDEX `fk_Locacao_Despachantes1_idx` (`FK_IDDespachante` ASC),
  INDEX `fk_Locacao_Veiculos1_idx` (`FK_IDVeiculo` ASC),
  CONSTRAINT `fk_Locacao_Clientes`
    FOREIGN KEY (`FK_IDClientes`)
    REFERENCES `locadoraVeiculos`.`Clientes` (`IDClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Despachantes1`
    FOREIGN KEY (`FK_IDDespachante`)
    REFERENCES `locadoraVeiculos`.`Despachantes` (`IDDespachantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Veiculos1`
    FOREIGN KEY (`FK_IDVeiculo`)
    REFERENCES `locadoraVeiculos`.`Veiculos` (`IDVeiculos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
